### PR TITLE
Allow HTML in custom error message

### PR DESCRIPTION
**Pull request by codente**

### CODE REVIEW

**Comment by justintadlock** [comment]
I'm not going to merge this PR for a couple of reasons.  1) It's on the wrong branch.  2) This is actually a more complex thing than the code in the PR (but easy to do).

I want to leave this ticket open though because this is a planned feature.

**Comment by codente** [comment]
Sorry wasn't sure what branch it is but the code I posted above works perfectly for my needs.  Glad to hear it is a planned feature :)

**Comment by justintadlock** [comment]
I need to add a branch and PR notice in the readme.  Generally speaking, Git repos have a "master" branch, which represents the latest stable release.  I don't accept PRs against the master.  I do plan to add a "dev" branch though to help with any confusion.

**Comment by justintadlock** [comment]
Fixed in https://github.com/justintadlock/members/commit/e1cadfca419884f88a5135ec31c6713555d83306

**Pull request closed without merging**
